version: '3.8'

services: 
  mysqldb:
    image: mysql
    env_file: ./.env
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATEBASE
    volumes:
      - dataDB:/var/lib/mysql
  
  nodeapp:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes: 
  dataDB: